service: serverless-meetup-debugging-tracing


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

