service: serverless-meetup-debugging-tracing

plugins:
  - serverless-plugin-tracing
  - serverless-plugin-aws-alerts

custom:
  alerts:
    topics:
      alarm: 
        topic: all-is-broken
        notifications:
          - protocol: email
            endpoint: blackhole@blackhole.io # set your proper mail here
    alarms:
      - functionErrors


provider:
  name: aws
  runtime: nodejs8.10
  tracing: true
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:GetRecords
        - kinesis:GetShardIterator
        - kinesis:PutRecord
        - kinesis:PutRecords
        - kinesis:DescribeStream
        - kinesis:ListStreams
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'


functions:
  hello:
    handler: handler.handleRequest
    events:
      - http:
          path: hello
          method: get
    environment:
      STREAM_NAME: ${file(./public.env.yml):${opt:stage, self:provider.stage}.eventStreamName}
      STREAM_ARN: ${file(./public.env.yml):${opt:stage, self:provider.stage}.eventStreamArn}
    alarms:
      - functionErrors
  
  processor:
    handler: processor.run
    events:
      - stream:
          arn: ${file(./public.env.yml):${opt:stage, self:provider.stage}.eventStreamArn}
          batchSize: 1
          startingPosition: LATEST
          enabeled: true
    

